name: clearml

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions: write-all

jobs:
  build_application:
    name: Compile with Python3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python 3.12
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: Install Python Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install --no-cache-dir -e .
          pip install setuptools

      - name: Build Python Package
        shell: bash
        run: python setup.py build

      - name: Tar Python Build
        shell: bash
        run: tar -czf python-build.tgz build

      - name: Upload Maven Build Repository
        uses: actions/upload-artifact@v4
        with:
          name: python-build
          path: python-build.tgz

      - name: Create Pip Dependency Tree
        shell: bash
        run: |
          pip install pipdeptree
          pipdeptree -fl --json > python_dep_tree.json

      - name: Upload Python Dependency Tree Zip
        uses: actions/upload-artifact@v4
        with:
          name: python-dependency-tree
          path: python_dep_tree.json

  create_sbom:
    needs: [ build_application ]
    name: Run SBOM Generation
    uses: seansmith39/H6060-Experiment-Workflows/.github/workflows/experiment_sbom_generation_python.yml@v1.0.1
    secrets: inherit

  run_sca_scanning:
    needs: [ build_application ]
    name: Run SCA Scanning Workflow
    uses: seansmith39/H6060-Experiment-Workflows/.github/workflows/experiment_1_sca_python.yml@v1.0.6
    secrets: inherit
    with:
      python-artifact-name: clearml
      python-source-dir: clearml
      snyk-file-to-scan: requirements.txt

  run_sast_scanning:
    needs: [ build_application ]
    name: Run SCA Scanning Workflow
    uses: seansmith39/H6060-Experiment-Workflows/.github/workflows/experiment_1_sast_python.yml@v1.0.6
    secrets: inherit
    with:
      deepsource-scan-enabled: false
      include-coverage-report: false
